version: "2.4"

services:
  ansible_dev:
    hostname: ansible_dev_${USERNAME}
    container_name: ansible_dev_${USERNAME}
    image: gitlab-docker-reg.local/cloud/automation/dev_container/ansible_dev:1.0.4
    #image: ansible_dev
    build: 
      #context: dev_container/ansible_dev 
      context: ansible_dev 
      network: host
      args:    
        - HTTP_PROXY=http://[240b:c0e0:101:5476:1c01:2::a]:3128
        - HTTPS_PROXY=http://[240b:c0e0:101:5476:1c01:2::a]:3128
        - http_proxy=http://[240b:c0e0:101:5476:1c01:2::a]:3128
        - https_proxy=http://[240b:c0e0:101:5476:1c01:2::a]:3128
    restart: unless-stopped
    networks:
      - network_1.2
    volumes:
      - ./share:/root/share
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/run/docker.sock:/var/run/docker.sock

    environment:
      - HTTP_PROXY=http://[240b:c0e0:101:5476:1c01:2::a]:3128
      - HTTPS_PROXY=http://[240b:c0e0:101:5476:1c01:2::a]:3128
      - http_proxy=http://[240b:c0e0:101:5476:1c01:2::a]:3128
      - https_proxy=http://[240b:c0e0:101:5476:1c01:2::a]:3128
networks:
  network_1.2:
    external: true
