version: '3'
services:
  ansible:
    container_name: dev_env
    build: .
    tty: true
    working_dir: '/root/'
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    cap_add:
      - SYS_ADMIN
    command: /sbin/init
